### ISSUE TITLE
Implement the entire assignment

### ISSUE THREAD

**Issue by EdwinVanRooij** [EdwinVanRooij/angular-assignment#1]
# Assignment

> Create a small angular application using angular 16. The application should have 2 forms. The first form should allow you to create a client with fields like Name, Surname, email and address (street name, post code, house number and city). The second form should allow you to view the list of all clients and view the details of a selected client. You are allowed to use any libraries you like. You do not have to spend too much time on the assignment but write the code like you would write it for production. Please also let us know how many hours you spent working on this. You can send us the github link, or Google or One Drive link for a zip file without node_modules folder. 

---

## Tasks

Since I'm doing this assignment alone (and it's relatively small), I'm going to put all of the tasks in this single issue. These tasks serve as a guide, not a strict list of requirements. This might take a bit longer than usually, since I'm programming on a relatively new machine, so there may be some time spent on software installations and configurations.

- [x] Create a GitHub repository
- [x] Project setup
- [x] Angular Material setup
- [x] Decide between NgRx & NgXs
  - [x] Setup chosen solution
  - [x] Mock initial sample clients
- [x] Form 1: display clients with details
	- [x] Create the page
	- [x] Display list of clients
	- [x] Display selected client details
- [x] Mock initial sample clients with an RxJs delay
- [x] Form 2: create a new client (pop-up)
	- [x] Create the pop-up
	- [x] Create the form
	- [x] Handle validation
	- [x] Send the newly created client to the backend (form in this case, with a service)
- [x] Polishing & debugging
	- [x] Add code documentation
	- [ ] Refactor details. Draw it out first, then redesign from scratch
	- [ ] Use static code analysis (SonarQube)
	- [x] Review Sami's feedback
- [ ] Add some unit tests
- [x] Placeholder component for overview
- [x] Placeholder component for details
- [ ] Custom theme matching the colors of Rabobank (blue and orange)
- [ ] PR review by myself, place comments, fix comments
- [x] Final functional test
- [x] Update Readme

**Comment by EdwinVanRooij** [comment]
I have made the decision to leave some tasks unfinished, since they were never really important and I've spent enough time on the assignment. 

>... you do not have to spend too much time on the assignment ...
